### ISSUE TITLE
Conversion from float64 to uint8 error on macosx backend

### ISSUE THREAD

**Issue by samjett247** [matplotlib/viscm#50] opened 2019-08-02 05:08 UTC
![image](https://user-images.githubusercontent.com/30481194/62345716-364c8280-b4a8-11e9-9978-7230f90ee47c.png)
This is an error I was getting from the command `python -m viscsm view <insert_colormap>`. I tried with jet and parula and viridis.
Versions:
viscm==0.0.7
matplotlib==1.12.0
colorspacious==1.1.2
numpy==1.17

**Comment by evertrol** [comment] 2019-08-22 11:44
This appears to be a duplicate of #46 .
Try upgrading to the most recent release, 0.8:
```
pip install --upgrade viscm
```
If that upgrade fails (it did for me; see also #48 ), try upgrading directly from the repository:
```
pip install --upgrade git+https://github.com/matplotlib/viscm.git
```

I'm using Python 3.7.3 with the repository version of viscm without a problem on MacOS.

**Comment by tacaswell** [comment] 2019-08-27 01:54
Closing this as fixed.  Please try upgrading to v0.9

**Closed as completed by tacaswell** 2019-08-27 01:54 UTC
